debug: True
thumbnails:
  small_root: ../media/
  large_root: ../media/
data_root: ../static/upload/fits
db:
  engine: django.db.backends.sqlite3
  name: ../db.sqlite3
astrometry_net:
  key:
  timeout: 200
api_doc:
  title: "Trailblazer API"
  version: "v1"
  description: "Trailblazer backend rest API"
  contact_email: "changethis@gmail.com"
  license:
    name: "MIT License"
    url: "https://github.com/dirac-institute/trailblazer/blob/main/LICENSE"