debug: True
thumbnails:
  small_root: ../media/
  large_root: ../media/
data_root: ../static/upload/fits
db:
  engine: django.db.backends.sqlite3
  name: ../db.sqlite3
astrometry_net:
  key:
  timeout: 200
